#!/bin/sh
# This file is part of LTSP, https://ltsp.github.io
# Copyright 2019 the LTSP team, see AUTHORS
# SPDX-License-Identifier: GPL-3.0-or-later

# Provide PAM authentication to a server via SSH and optionally SSHFS $HOME.
# It's not an LTSP applet in order to be able to run without LTSP.
# It may be called by the user (see install below),
# or by pam_exec, either as root for the initial login,
# or as the user for screensaver unlocking etc.

die() {
    printf "%s\n" "$*" >&2
    exit 1
}

require_root() {
    if [ "$_UID" != "0" ]; then
        die "${1:-$0 must be run as root}"
    fi
}

# Install pamltsp in the system PAM configuration.
install() {
    local search replace

    require_root
    sed 's/.*\(KillUserProcesses=\).*/\1yes/' -i /etc/systemd/logind.conf
    # The seteuid option is needed for `getent shadow`, for mkdir/chown $HOME,
    # for caching shadow options to /run/ltsp/pam/, for using systemd-run etc.
    # These are Debian/Ubuntu specific:
    search="^auth\t\[success=1 default=ignore\]\tpam_unix.so nullok_secure$"
    replace="auth\t\[success=2 default=ignore\]\tpam_unix.so nullok_secure\n\
auth\t\[success=1 default=ignore\]\tpam_exec.so seteuid expose_authtok stdout quiet $_SELF pam_auth"
    sed "s|$search|$replace|" -i /etc/pam.d/common-auth
    grep -qw "pamltsp" /etc/pam.d/common-auth ||
        die "Could not configure PAM for SSH authentication!"
    printf "session optional\tpam_exec.so seteuid stdout quiet %s\n" \
        "$_SELF pam_session" >> /etc/pam.d/common-session
}

# May be called:
# As root by pam auth, for SSH or SSHFS or passwordless logins
# As root by pam open_session, for autologins
# As user by pam auth, for screensaver unlocking
# As the user doesn't have enough rights to `getent shadow`;
# necessary information should be cached in /run/ltsp/pam/ on login.
pam_auth() {
    local pw_entry pw_name pw_passwd pw_uid pw_gid pw_gecos pw_dir \
        pw_shell sp_entry sp_namp sp_pwdp dummy msg

    pam_log
    # Verify that we're being called from PAM and that the user exists
    if [ -z "$PAM_USER" ] || ! pw_entry=$(getent passwd "$PAM_USER"); then
        die "User $PAM_USER doesn't exist"
    fi
    # Retrieve the user's sp_entry from shadow or cache
    if [ "$_UID" = "0" ]; then
        sp_entry=$(getent shadow "$PAM_USER")
    elif [ -f "/run/ltsp/pam/$PAM_USER/shadow" ]; then
        sp_entry=$(cat "/run/ltsp/pam/$PAM_USER/shadow")
    else
        # We can't retrieve it; assume they're not a pamltsp user
        exit 1
    fi
    IFS=:
    # Variable names from `man getpwent/getspent`
    read -r pw_name pw_passwd pw_uid pw_gid pw_gecos pw_dir pw_shell <<EOF
$pw_entry
EOF
    read -r sp_namp sp_pwdp dummy<<EOF
$sp_entry
EOF
    test "$_OLDIFS" = "not set" && unset IFS || IFS="$_OLDIFS"
    test "$pw_name" = "$sp_namp" || die "Invalid passwd/shadow for $PAM_USER"
    if [ "${sp_pwdp}" = "${sp_pwdp#pamltsp}" ]; then
        if [ "$PAM_TYPE" = "open_session" ]; then
            exit 0
        else
            # TODO: delete this message in production and just exit 1
            die "User $PAM_USER can't auth via pamltsp"
        fi
    fi
    # First call since boot
    if [ ! -d /run/ltsp/pam ]; then
        mkdir -p /run/ltsp/pam
        if [ "$SSHFS" != "0" ]; then
            # On SSHFS gnome-keyring requires disable_hardlinks, but this
            # breaks ICEauthority, so just disable gnome-keyring for now
            # https://bugzilla.gnome.org/show_bug.cgi?id=730587
            # TODO: ssh -X user@localhost from an ltsp client fails too:
            # /usr/bin/xauth: timeout in locking authority file /home/user/.Xauthority
            # It's probably not important; plain `xhost +local:` is OK for DIRECTX.
            if [ -x /usr/bin/gnome-keyring ]; then
                chmod -x /usr/bin/gnome-keyring
            fi
        fi
    fi
    # Cache the shadow entry for screensaver and passwordless authentication
    if [ "$_UID" = 0 ]; then
        # TODO: change that to 700 if we need .ICEauthority here
        mkdir -p -m 500 "/run/ltsp/pam/$pw_name"
        chown "$pw_uid:$pw_gid" "/run/ltsp/pam/$pw_name"
        echo "$sp_entry" > "/run/ltsp/pam/$pw_name/shadow"
    fi
    # Support "pamltsp=" for passwordless logins without SSH authentication
    # for guest-like accounts with NFS/local home.
    pass=${sp_pwdp#pamltsp}
    pass=${pass%%,*}
    test "$pass" = "=" && return 0
    # jessie-mate breaks with IdentityFile=/dev/null and shows:
    #   Enter passphrase for key '/dev/null':
    # It works with IdentityFile=/nonexistent
    set -- -F /dev/null -o UserKnownHostsFile="/etc/ltsp/ssh_known_hosts" \
        -o IdentitiesOnly=yes -o IdentityFile=/nonexistent \
        -o NumberOfPasswordPrompts=1
    unset success
    # Indicate that an authentication attempt is in progress
    # See https://github.com/libfuse/sshfs/issues/183
    trap "rm -f '/run/ltsp/pam/$PAM_USER/pid'" HUP INT QUIT SEGV PIPE TERM EXIT
    echo "$$" > "/run/ltsp/pam/$PAM_USER/pid"
    # `mountpoint` blocks until the sshfs password in entered.
    # That may be a good thing, to avoid race conditions.
    if [ "$SSHFS" = "0" ] || mountpoint -q /home || mountpoint -q "$pw_dir"
    then
        if [ "$PAM_TYPE" = "open_session" ]; then
            # This point is reached when we already mounted home in auth,
            # or for passwordless logins with NFS/local home.
            # In these cases we want to skip SSH authentication.
            exit 1
        fi
        # The ssh call logic is documented in ssh-askpass
        export DISPLAY=
        export SSH_ASKPASS="${_SELF%/*}/ssh-askpass"
        if ssh -q "$@" "$pw_name@$SERVER" exit 0; then
            success=1
            if [ ! -e "$pw_dir" ] && [ "$MKHOMEDIR" != "0" ]; then
                # Emulate pam_mkhomedir
                mkdir -p -m 0755 "$pw_dir"
                cp -a /etc/skel/. "$pw_dir"
                chown -R "$pw_uid:$pw_gid" "$pw_dir"
            fi
        fi
    else
        test "$_UID" = 0 || die "SSHFS needed without root?!"
        # $pw_dir must not be in use to be mounted; cd elsewhere
        cd / || true
        # If a previous sshfs was killed instead of properly unmounted,
        # `mountpoint` returns 1 "Transport endpoint is not connected",
        # yet the mount point is there in /proc/mounts, and a new sshfs fails.
        # Run an extra fusermount for this case.
        # To reproduce, login as admin, and run: systemctl stop gdm3
        # It needs a few seconds to kill all the processes.
        # Logins will fail for those seconds, and work properly afterwards.
        grep -qs "$pw_dir fuse.sshfs" /proc/mounts && fusermount -u "$pw_dir"
        # Create an empty home dir if it's not there; nope, no skel for SSHFS
        if [ ! -d "$pw_dir" ] && [ "$MKHOMEDIR" != "0" ]; then
            mkdir -p -m 0755 "$pw_dir"
            chown "$pw_uid:$pw_gid" "$pw_dir"
        fi
        # SSHFS doesn't appear to support SSH_ASKPASS, but it can read stdin
        # TODO: but why doesn't it read it directly from pam_exec?
        # allow_other,default_permissions: allow the user but not other users
        # We don't use `sudo -u` for sshfs to avoid modprobe'ing fuse,
        # sed'ing fuse.conf, chown'ing home etc; if we did, that would be:
        # allow_root: for the DM to setup .Xauthority
        # nonempty: in case of .bash_history or local home
        if "${_SELF%/*}/ssh-askpass" |
            sshfs -o password_stdin,allow_other,default_permissions,nonempty \
            "$@" "$pw_name@$SERVER:" "$pw_dir"
        then
            success=1
        fi
    fi
    if [ "$success" = "1" ]; then
        return 0
    else
        # su: gettext -d Linux-PAM "Authentication failure"
        # login: gettext -d shadow 'Login incorrect' (this works in fedora30 too)
        msg=$(gettext -d shadow "Login incorrect")
        msg=${msg:-Authentication failure}
        echo ".$msg." >&2
        return 1
    fi
}

pam_log() {
    # TODO: remove logging in production
    {
        id
        env
        ps faux
        grep home /proc/self/mountinfo
    } >"/tmp/pam_$PAM_TYPE.$$"
}

pam_session() {
    pam_log
    case "$PAM_TYPE" in
        close_session) unmount_sshfs; return 0 ;;
        open_session) pam_auth; return 0 ;;
    esac
}

unmount_sshfs() {
    local pw_entry pw_name pw_passwd pw_uid pw_gid pw_gecos pw_dir pw_shell

    # Verify that we're being called from PAM and that the user exists
    if [ -z "$PAM_USER" ] || ! pw_entry=$(getent passwd "$PAM_USER"); then
        die "User $PAM_USER doesn't exist"
    fi
    IFS=:
    # Variable names from `man getpwnam`
    read -r pw_name pw_passwd pw_uid pw_gid pw_gecos pw_dir pw_shell <<EOF
$pw_entry
EOF
    test "$_OLDIFS" = "not set" && unset IFS || IFS="$_OLDIFS"

    # If $HOME isn't SSHFS, exit
    grep -qs "$pw_dir fuse.sshfs" /proc/mounts || return 0

    # TODO: only run this as root
    # TODO: --quiet isn't supported in jessie-mate
    # Tell systemd not to wait nor to kill this:
    systemd-run --scope "$_SELF" unmount_sshfs_stage2 \
        "$PAM_USER" "$pw_dir" >/dev/null 2>/dev/null </dev/null &
    # Without this sleep, systemd-run works 100% on vt2, 10% on GUI
    sleep 0.1
    return 0
}

# This runs with no file descriptors open, to be properly backgrounded
unmount_sshfs_stage2() {
    local pw_name pw_dir i cmdline1 cmdline2

    pw_name=$1
    pw_dir=$2
    # This isn't called from pam; just emulating it for pam_log
    PAM_TYPE=unmount
    pam_log
    read -r cmdline1 <"/proc/$$/cmdline"
    # Kill all other unmount_sshfs_stage2 of the same user; we're taking over!
    for i in $(pidof -x "$_SELF"); do
        test "$i" != "$$" || continue
        read -r cmdline2 <"/proc/$i/cmdline"
        test "$cmdline1" = "$cmdline2" || continue
        kill "$i"
    done
    i=0
    # Allow up to 10 seconds for systemd process killing and cleanup.
    # Check every second if it finished.
    while [ "$i" -lt 10 ]; do
        sleep 1
        # If it was... manually unmounted?
        grep -qs "$pw_dir fuse.sshfs" /proc/mounts || return 0
        # If a login for this same user is being attempted, postpone
        if [ -e "/run/ltsp/pam/$PAM_USER/pid" ]; then
            continue
        else
            i=$((i+1))
        fi
        # If no user processes are running, unmount it
        if [ "$(pgrep -cu "$pw_name")" = "0" ]; then
            fusermount -u "$pw_dir"
            return 0
        fi
    done
}

main() {
    local func _OLDIFS _SELF

    _OLDIFS="${IFS-not set}"
    _SELF=$(readlink -f "$0")
    _UID=$(id -u)
    umask 0022
    # TODO: read these from a configuration file
    # SSHFS=1  # The default
    SERVER=server
    case "$1" in
        install|pam_auth|pam_session|unmount_sshfs_stage2)
            func=$1
            shift
            $func "$@"
            ;;
        *) die "Usage: $0 <install|pam_auth|pam_session> [params], not |$*|" ;;
    esac
}

main "$@"
