# This file is part of LTSP, https://ltsp.github.io
# Copyright 2019 the LTSP team, see AUTHORS
# SPDX-License-Identifier: GPL-3.0-or-later

# Handle tasks related to display managers

display_manager_main() {
    re configure_lightdm
    re configure_gdm
}

configure_lightdm() {
    is_command lightdm || return 0
    grep -qsw ^autologin-user /etc/lightdm/lightdm.conf &&
        rw sed 's|^ *autologin-user *=.*|# ltsp: &|' \
            -i /etc/lightdm/lightdm.conf
    re mkdir -p /etc/lightdm/lightdm.conf.d
    re echo "# Generated by \`ltsp init\`, see man:ltsp(8)
# Work around https://github.com/CanonicalLtd/lightdm/issues/49
[Seat:*]
greeter-show-manual-login = true" > /etc/lightdm/lightdm.conf.d/ltsp.conf
}

configure_gdm() {
    is_command gdm3 || return 0
    # Disable autologin
    grep -qsw "^ *AutomaticLoginEnable *=.*rue" /etc/gdm3/daemon.conf &&
        rw sed "s|^ *AutomaticLoginEnable *=.*rue|# ltsp: &|" \
            -i /etc/gdm3/daemon.conf
}
